### ISSUE TITLE
Todo for V1

### ISSUE THREAD

**Issue by willtham1** [willtham1/TheRaffle#1]
- [x] User must be able to drag and drop file from Shopify into CLI
- [x] CLI must be able to take file and read for headers
- [x] Once headers (name) has been detected scan for dupes
