### ISSUE TITLE
Todo Stage 2

### ISSUE THREAD

**Issue by willtham1** [willtham1/TheRaffle#2]
- [x] As the user I want to be able to control now many winners there can be. (1, 6,9,100)
- [x] But before I randomize the raffle I want to be able to input a name that matches within the csv to become a winner
- [x] For clean sake add Console.WriteLine as a status to let the user know its working and done
